"""Synthetic market data - **for pipeline self-testing only**.

.. danger::
   Nothing produced by this module is market data. It is a random process with
   an injected pattern, used to prove that the download-to-report pipeline runs
   end to end and that the code detects a pattern *it was told to inject*.

   No number derived from synthetic data may appear in ``research_report.md``,
   in the dashboard's backtest pages, or in any statement about whether the
   momentum hypothesis is true. Every artefact generated from it is written
   under ``data/synthetic/`` and carries a ``SYNTHETIC`` banner.

The generator is a geometric random walk with:

* fat-tailed innovations (Student-t) - crypto minute returns are not Gaussian;
* volatility clustering (a simple GARCH-like update);
* injected momentum events with a *configurable* continuation probability, so
  tests can assert that the system finds an edge when one exists and finds none
  when it does not;
* occasional missing bars, to exercise the gap-handling paths;
* an intraday volume profile.
"""

from __future__ import annotations

from dataclasses import dataclass

import numpy as np
import pandas as pd

from .logging_utils import get_logger

log = get_logger(__name__)

SYNTHETIC_BANNER = (
    "SYNTHETIC DATA - generated by bitvavo_momentum.synthetic. "
    "NOT market data. NOT a research result."
)


@dataclass
class SyntheticConfig:
    n_minutes: int = 60 * 24 * 120          # 120 days of 1-minute bars
    start: str = "2024-01-01T00:00:00Z"
    base_price: float = 1.0
    drift_per_minute: float = 0.0
    base_vol_per_minute: float = 0.0025
    vol_persistence: float = 0.94
    vol_shock: float = 0.05
    t_degrees_of_freedom: float = 4.0
    event_probability_per_bar: float = 0.00035   # ~0.5 events/day
    event_magnitude: tuple[float, float] = (0.10, 0.14)
    event_duration_minutes: tuple[int, int] = (60, 180)
    continuation_probability: float = 0.5        # 0.5 == no edge
    continuation_magnitude: tuple[float, float] = (0.01, 0.05)
    missing_bar_probability: float = 0.01
    base_volume: float = 1000.0
    event_volume_multiplier: float = 6.0
    seed: int = 20260802


def generate_market(
    market: str = "SYN-EUR",
    config: SyntheticConfig | None = None,
    seed_offset: int = 0,
) -> pd.DataFrame:
    """Generate one synthetic OHLCV series. Returns a tidy candle frame."""
    config = config or SyntheticConfig()
    rng = np.random.default_rng(config.seed + seed_offset)
    n = config.n_minutes

    # --- volatility path (clustered) ---------------------------------------
    vol = np.empty(n)
    vol[0] = config.base_vol_per_minute
    shocks = rng.standard_t(config.t_degrees_of_freedom, size=n) / np.sqrt(
        config.t_degrees_of_freedom / (config.t_degrees_of_freedom - 2)
    )
    for i in range(1, n):
        vol[i] = np.sqrt(
            (1 - config.vol_persistence) * config.base_vol_per_minute**2
            + config.vol_persistence * vol[i - 1] ** 2
            + config.vol_shock * (vol[i - 1] * shocks[i - 1]) ** 2 * 0.01
        )

    returns = config.drift_per_minute + vol * shocks

    # --- injected momentum events ------------------------------------------
    event_starts: list[int] = []
    i = 0
    while i < n - 1:
        if rng.random() < config.event_probability_per_bar:
            duration = int(rng.integers(*config.event_duration_minutes))
            magnitude = float(rng.uniform(*config.event_magnitude))
            end = min(n - 1, i + duration)
            per_bar = np.log1p(magnitude) / max(1, end - i)
            returns[i:end] += per_bar
            event_starts.append(end)

            # Continuation or reversal after the event, per the configured edge.
            follow = int(rng.integers(30, 240))
            follow_end = min(n - 1, end + follow)
            move = float(rng.uniform(*config.continuation_magnitude))
            sign = 1.0 if rng.random() < config.continuation_probability else -1.0
            if follow_end > end:
                returns[end:follow_end] += sign * np.log1p(move) / (follow_end - end)
            i = follow_end
        else:
            i += 1

    close = config.base_price * np.exp(np.cumsum(returns))

    # --- OHLC from the close path ------------------------------------------
    open_ = np.concatenate([[config.base_price], close[:-1]])
    noise = np.abs(rng.normal(0, 1, size=n)) * vol * close
    high = np.maximum(open_, close) + noise
    low = np.minimum(open_, close) - noise
    low = np.maximum(low, 1e-12)

    index = pd.date_range(start=config.start, periods=n, freq="1min", tz="UTC")
    minute_of_day = np.asarray(index.hour, dtype="float64") * 60 + np.asarray(index.minute, dtype="float64")
    profile = 1.0 + 0.5 * np.sin(2 * np.pi * minute_of_day / 1440.0)
    volume = config.base_volume * profile * np.exp(rng.normal(0, 0.4, size=n))
    for start in event_starts:
        window = slice(max(0, start - 120), min(n, start + 60))
        volume[window] *= config.event_volume_multiplier

    frame = pd.DataFrame(
        {
            "timestamp": index,
            "open": open_,
            "high": high,
            "low": low,
            "close": close,
            "volume": volume,
        }
    )

    if config.missing_bar_probability > 0:
        keep = rng.random(n) >= config.missing_bar_probability
        keep[0] = keep[-1] = True
        frame = frame[keep].reset_index(drop=True)

    frame.attrs["market"] = market
    frame.attrs["synthetic"] = True
    frame.attrs["banner"] = SYNTHETIC_BANNER
    return frame


def generate_universe(
    n_markets: int = 8,
    config: SyntheticConfig | None = None,
    include_references: bool = True,
) -> dict[str, pd.DataFrame]:
    """Generate a small synthetic universe including BTC/ETH stand-ins."""
    config = config or SyntheticConfig()
    universe: dict[str, pd.DataFrame] = {}

    if include_references:
        # References are calmer and event-free, like large caps relative to alts.
        ref_config = SyntheticConfig(
            **{**config.__dict__, "base_vol_per_minute": config.base_vol_per_minute * 0.4,
               "event_probability_per_bar": 0.0, "base_price": 40000.0}
        )
        universe["BTC-EUR"] = generate_market("BTC-EUR", ref_config, seed_offset=1)
        eth_config = SyntheticConfig(**{**ref_config.__dict__, "base_price": 2500.0})
        universe["ETH-EUR"] = generate_market("ETH-EUR", eth_config, seed_offset=2)

    for i in range(n_markets):
        name = f"SYN{i:02d}-EUR"
        universe[name] = generate_market(name, config, seed_offset=100 + i)
    log.info("Generated %d synthetic markets (%s)", len(universe), SYNTHETIC_BANNER)
    return universe
