"""
Email delivery for daily dashboard reports.

Uses Gmail SMTP with an App Password (no third-party service needed).
Credentials loaded from environment variables — never hardcoded.

Required env vars (set in .env):
  GMAIL_SENDER      — Gmail address to send FROM (can be same as recipient)
  GMAIL_APP_PASSWORD — 16-char App Password from myaccount.google.com/security
  ALERT_EMAIL_TO    — Recipient address
"""
from __future__ import annotations

import os
import smtplib
import ssl
from datetime import date
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from pathlib import Path

from core.logging import get_logger

log = get_logger("reporting.email")


def send_dashboard(html_path: Path, subject: str | None = None) -> bool:
    """
    Send the HTML dashboard as an email.

    Returns True on success, False on failure (never raises — safe to call
    from cron without crashing the whole session).
    """
    sender   = os.getenv("GMAIL_SENDER", "").strip()
    password = os.getenv("GMAIL_APP_PASSWORD", "").strip()
    recipient = os.getenv("ALERT_EMAIL_TO", "anantrajsingh7@gmail.com").strip()

    if not sender or not password:
        log.warning(
            "Email not configured. Set GMAIL_SENDER and GMAIL_APP_PASSWORD in .env"
        )
        return False

    if not html_path.exists():
        log.error("Dashboard file not found: %s", html_path)
        return False

    today = date.today()
    subject = subject or f"Quant Platform Dashboard — {today.strftime('%A, %B %d, %Y')}"
    html_body = html_path.read_text(encoding="utf-8")

    msg = MIMEMultipart("alternative")
    msg["Subject"] = subject
    msg["From"]    = f"Quant Platform <{sender}>"
    msg["To"]      = recipient

    # Plain-text fallback
    plain = (
        f"Quant Platform Daily Dashboard — {today.strftime('%B %d, %Y')}\n\n"
        "Open this email in an HTML-capable client to view the dashboard.\n\n"
        "Generated by Quant Platform v1.0 — for research purposes only."
    )
    msg.attach(MIMEText(plain, "plain"))
    msg.attach(MIMEText(html_body, "html"))

    try:
        context = ssl.create_default_context()
        with smtplib.SMTP_SSL("smtp.gmail.com", 465, context=context) as smtp:
            smtp.login(sender, password)
            smtp.sendmail(sender, recipient, msg.as_string())
        log.info("Dashboard emailed to %s", recipient)
        return True
    except smtplib.SMTPAuthenticationError:
        log.error(
            "Gmail auth failed. Check GMAIL_SENDER and GMAIL_APP_PASSWORD in .env.\n"
            "App Password must be 16 chars with no spaces."
        )
        return False
    except Exception as e:
        log.error("Email send failed: %s", e)
        return False


def test_connection() -> bool:
    """Quick connectivity test — sends a short test email."""
    sender   = os.getenv("GMAIL_SENDER", "").strip()
    password = os.getenv("GMAIL_APP_PASSWORD", "").strip()
    recipient = os.getenv("ALERT_EMAIL_TO", "anantrajsingh7@gmail.com").strip()

    if not sender or not password:
        print("ERROR: GMAIL_SENDER and GMAIL_APP_PASSWORD not set in .env")
        return False

    msg = MIMEText("Quant Platform email delivery is working correctly.", "plain")
    msg["Subject"] = "Quant Platform — Test Email"
    msg["From"]    = f"Quant Platform <{sender}>"
    msg["To"]      = recipient

    try:
        context = ssl.create_default_context()
        with smtplib.SMTP_SSL("smtp.gmail.com", 465, context=context) as smtp:
            smtp.login(sender, password)
            smtp.sendmail(sender, recipient, msg.as_string())
        print(f"Test email sent to {recipient}")
        return True
    except Exception as e:
        print(f"FAILED: {e}")
        return False


if __name__ == "__main__":
    test_connection()
